---
title: "Privacy policy for gcalendr access to Google Calendar API"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Privacy policy for gcalendr access to Google Calendar API}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


<!--
Heavily inspired by:
* The tidyverse privacy policy at https://www.tidyverse.org/google_privacy_policy/
-->

The `gcalendr` package makes it easier to work with  the Google Calendar APIs from R.

This packages is governed by common policies recorded here. This package uses internal resources owned by the "Gcalendr" project on Google Cloud Platform. That is the name you will see in a consent screen.

<!--
*Exception: gmailr does NOT use any resources owned by `gcalendr` package, due to [special requirements around Gmail and its scopes](https://developers.google.com/terms/api-services-user-data-policy#additional-requirements-for-specific-api-scopes). You MUST provide your own OAuth client to gmailr, whereas that is possible, but not mandatory, for the other packages listed here.*
-->

Your use of Google APIs with the `gcalendr` package is subject to the Google Calendar API 
terms of service. See <https://developers.google.com/terms/>.


# Privacy

## Google account and user data

### Accessing user data

This package access Google resources from your local machine. Your machine communicates directly with the Google APIs.

The `gcalendr` package project never receives your data or the permission to access your data. The owners of the project can only see anonymous, aggregated information about usage of tokens obtained through its OAuth client, such as which APIs and endpoints are being used.

Each package includes functions that you can execute in order to read or modify your own data. This can only happen after you provide a token, which requires that you authenticate yourself as a specific Google user and authorize these actions. 

This package can help you get a token by guiding you through the OAuth flow in the browser. There you must consent to allow the `gcalendr` package to operate on your behalf. The OAuth consent screen will describe the scope of what is being authorized, e.g., it will name the target API(s) and whether you are authorizing "read only" or "read and write" access.

There are two ways to use this package without authorizing the `gcalendr` package: bring your own [service account token](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) or configure the package to use an OAuth client of your choice.

### Scopes

At the moment the `gcalendr` package only provides read-only access to the API. Here is an overview of the scopes requested by the `gcalendr` package and their rationale:

Scope |  Purpose
----- | ----------
[calendar.readonly](https://www.googleapis.com/auth/calendar.readonly)                    |	read-only access to Calendars
[calendar.events](https://www.googleapis.com/auth/calendar.events)                        |	read-only access to Events
[calendar.events.readonly](https://www.googleapis.com/auth/calendar.events.readonly)      |	read-only access to Events
[calendar.settings.readonly](https://www.googleapis.com/auth/calendar.settings.readonly)  |	read-only access to Settings


### Sharing user data

The packages only communicate with Google APIs. No user data is shared with the owners of the `gcalendr` package, RStudio, or any other servers.


### Storing user data

This package may store your credentials on your local machine, for later reuse by you. **Use caution when using this package on a shared machine**.

By default, an OAuth token is cached in a local file, such as `~/.R/gargle/gargle-oauth`. See the documentation for [`gargle::gargle_options()`](https://gargle.r-lib.org/reference/gargle_options.html) and [`gargle::credentials_user_oauth2()`](https://gargle.r-lib.org/reference/credentials_user_oauth2.html) for information on how to control the location of the token cache or suppress token caching, globally or at the individual token level.


# Policies for authors of packages or other applications

Do not use an API key or client ID from the `gcalendr` package in an external package or tool. Per the Google User Data Policy
<https://developers.google.com/terms/api-services-user-data-policy>, your
application must accurately represent itself when authenticating to Google API services.

If you use this package inside another package or application that executes its own logic --- as opposed to code in the `gcalendr` package or by the user --- you must communicate this clearly to the user. Do not use credentials from the `gcalendr` package; instead, use credentials associated with your project or your user.
